# Generated by Django 4.2 on 2023-07-07 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='نام برند')),
                ('brand_logo_image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر برند کالا')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50, verbose_name='نام ویژگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='نام کالا')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کالا')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('register_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ درج')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_of_brands', to='products.brand', verbose_name='برند کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='ProductImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کالا')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product', verbose_name='نام کالا')),
            ],
            options={
                'verbose_name': 'گالری تصاویر محصول',
                'verbose_name_plural': 'گالری تصاویر محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='گروه کالا')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر گروه کالا')),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('register_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ درج')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='products.productgroup', verbose_name='والد گروه کالا')),
            ],
            options={
                'verbose_name': 'گروه کالا',
                'verbose_name_plural': 'گروه های کالا',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(max_length=50, verbose_name='مقدار ویژگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_of_product', to='products.product', verbose_name='نام کالا')),
            ],
            options={
                'verbose_name': 'ویژگی کالا',
                'verbose_name_plural': 'ویژگی های کالاها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ManyToManyField(related_name='products_of_groups', to='products.productgroup', verbose_name='گروه کالا'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product_group',
            field=models.ManyToManyField(related_name='features_of_product_group', to='products.productgroup', verbose_name='گروه کالا'),
        ),
    ]
