# Generated by Django 4.2 on 2023-07-29 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_brand_brand_logo_image_and_more'),
        ('accounts', '0009_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ سفارش')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش سفارش')),
                ('is_finally', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد منجصر به فرد سفارش')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف روی فاکتور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderDeatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت کالا در فاکتور')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_deatails1', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_deatails2', to='products.product', verbose_name='کالا')),
            ],
        ),
    ]
