# Generated by Django 4.2 on 2023-05-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile_nummber',
            new_name='mobile_number',
        ),
    ]
