# Generated by Django 4.2 on 2023-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_newssletter',
            field=models.BooleanField(default=False, verbose_name='ارسال خبرنامه'),
        ),
    ]
