# Generated by Django 4.2 on 2023-07-31 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_remove_customer_phone_number'),
        ('orders', '0002_paymenttype_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت پرداخت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش پرداخت')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداخت')),
                ('decription', models.TextField(verbose_name='توضیحات پرداخت')),
                ('is_finally', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت درگاه پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری پرداخت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_customer', to='accounts.customer', verbose_name='مشتری')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
