# Generated by Django 4.2 on 2023-08-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehauses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehause',
            old_name='warehaus_taype',
            new_name='warehaus_type',
        ),
    ]
